---
deployment:
  tasks:
    - export DEPLOYPATH=/home/milanr/public_html
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R ./* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
