---
deployment:
  tasks:
    - git pull origin staging
    - export DEPLOYPATH=/home/milanr/public_html && echo "Deployment started at $(date)" >> /home/milanr/logs/deployment.log 2>&1
    - /bin/cp -R ./* $DEPLOYPATH/ >> /home/milanr/logs/deployment.log 2>&1
